// <auto-generated />
using Konyvkatalogus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvkatalogus.Migrations
{
    [DbContext(typeof(KonyvContext))]
    partial class KonyvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Konyvkatalogus.Model.Konyv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Isbn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KiadaIdeje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("konyvek");
                });
#pragma warning restore 612, 618
        }
    }
}
